server:
  port: 8082
  servlet:
    context-path: /identity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  main:
    allow-bean-definition-overriding: true

jwt:
  signerKey: "vBsGNGftcdp1lFPk8/rRPmP6UUdBgxEvjST8owijFtyRPSvnPKXQNVr9A7lEYa4T"
