server:
  port: 8888
  application:
    name: api-gateway
spring:
  cloud:
    gateway:
      mvc:
        routes:
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=/profile/**
        - id: auth_service
          uri: http://localhost:8082
          predicates:
            - Path=/identity/**
        - id: product_service
          uri: http://localhost:8083
          predicates:
            - Path=/product/**
        - id: cart_service
          uri: http://localhost:8085
          predicates:
            - Path=/cart/**
        - id: order_service
          uri: http://localhost:8088
          predicates:
            - Path=/order/**
        - id: shipping_service
          uri: http://localhost:8086
          predicates:
            - Path=/shipping/**