server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/profile_db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
