server:
  port: 8085
  servlet:
    context-path: /cart
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cart_db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update